service: awsoverflow

provider:
  name: aws
  runtime: python3.6
  region: us-west-2
  stage: dev
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux


functions:
  helloWorld:
    handler: handler.hello_world
    events:
      - http:
          path: helloworld
          method: get
          cors: true

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: myserverlessprojectuploadbucket1
