service: awsoverflow

provider:
  name: aws
  runtime: python3.6
  region: us-west-2
  stage: dev


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: echo/hello
          method: get
resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: myserverlessprojectuploadbucket1
